name: CI macOS
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  Run_checks:
    strategy:
      matrix:
        os: [macOS-latest]
        node_version: ["20"]
        java: ["17"]
      fail-fast: false
    env:
      NX_VERBOSE_LOGGING: "true"
      NX_MAVEN_CLI_OPTS: "--no-transfer-progress -Dmaven.plugin.validation=VERBOSE"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i

      - name: Maven-checkstyle-lint
        run: npm run nx run-many -- --target=maven-checkstyle-lint

      - name: Gradle-checkstyle-lint
        run: npm run nx run-many -- --target=gradle-checkstyle-lint

      - name: Ktlint
        run: npm run nx run-many -- --target=ktlint

      - name: Unit tests
        run: npm run nx run-many -- --target=test

      - name: Build
        run: npm run nx run-many -- --target=build
